version: '3.9'

services:

  postgres-user:
    image: postgres:16-alpine
    container_name: postgres-user
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  postgres-product:
    image: postgres:16-alpine
    container_name: postgres-product
    restart: always
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  postgres-order:
    image: postgres:16-alpine
    container_name: postgres-order
    restart: always
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  postgres-payment:
    image: postgres:16-alpine
    container_name: postgres-payment
    restart: always
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
    networks:
      - microservices-net


volumes:
  user_data:
  product_data:
  order_data:
  payment_data:

networks:
  microservices-net:
    driver: bridge